/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.alcreta.gui;

import net.alcreta.ahorcado.Ahorcado;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * La interfaz principal del juego
 *
 * @author Alvaro
 */
public final class Gui extends javax.swing.JFrame {

    Ahorcado oAhorcado = new Ahorcado();

    /**
     * Creates new form gui
     */
    public Gui() {
        initComponents();
        oAhorcado.cargarPalabras();
        oAhorcado.cargarJugadores();
        //oAhorcado
        resetearJuego();
        Login oLogin = new Login(this);
        setVisible(false);
        setLocationRelativeTo(null);

    }

    public Ahorcado getoAhorcado() {
        return oAhorcado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonI = new javax.swing.JButton();
        jButtonH = new javax.swing.JButton();
        jButtonG = new javax.swing.JButton();
        jButtonF = new javax.swing.JButton();
        jButtonE = new javax.swing.JButton();
        jButtonD = new javax.swing.JButton();
        jButtonC = new javax.swing.JButton();
        jButtonB = new javax.swing.JButton();
        jButtonA = new javax.swing.JButton();
        jButtonJ = new javax.swing.JButton();
        jButtonK = new javax.swing.JButton();
        jButtonL = new javax.swing.JButton();
        jButtonM = new javax.swing.JButton();
        jButtonN = new javax.swing.JButton();
        jButtonNy = new javax.swing.JButton();
        jButtonO = new javax.swing.JButton();
        jButtonP = new javax.swing.JButton();
        jButtonQ = new javax.swing.JButton();
        jButtonR = new javax.swing.JButton();
        jButtonS = new javax.swing.JButton();
        jButtonT = new javax.swing.JButton();
        jButtonU = new javax.swing.JButton();
        jButtonV = new javax.swing.JButton();
        jButtonW = new javax.swing.JButton();
        jButtonX = new javax.swing.JButton();
        jButtonY = new javax.swing.JButton();
        jButtonZ = new javax.swing.JButton();
        jButtonNuevoJuego = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelPalabraOculta = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextFieldAgregar = new javax.swing.JTextField();
        jButtonAgregarPalabra = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jTextFieldEliminar = new javax.swing.JTextField();
        jButtonEliminarPalabra = new javax.swing.JButton();
        jLabelImagen = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemJugadorEstadisticas = new javax.swing.JMenuItem();
        jMenuItemJugadorCambiar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jButtonI.setText("I");
        jButtonI.setMaximumSize(new java.awt.Dimension(45, 23));
        jButtonI.setMinimumSize(new java.awt.Dimension(45, 23));
        jButtonI.setPreferredSize(new java.awt.Dimension(46, 23));
        jButtonI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIActionPerformed(evt);
            }
        });

        jButtonH.setText("H");
        jButtonH.setMaximumSize(new java.awt.Dimension(45, 23));
        jButtonH.setMinimumSize(new java.awt.Dimension(45, 23));
        jButtonH.setPreferredSize(new java.awt.Dimension(46, 23));
        jButtonH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHActionPerformed(evt);
            }
        });

        jButtonG.setText("G");
        jButtonG.setMaximumSize(new java.awt.Dimension(45, 23));
        jButtonG.setMinimumSize(new java.awt.Dimension(45, 23));
        jButtonG.setPreferredSize(new java.awt.Dimension(46, 23));
        jButtonG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGActionPerformed(evt);
            }
        });

        jButtonF.setText("F");
        jButtonF.setMaximumSize(new java.awt.Dimension(45, 23));
        jButtonF.setMinimumSize(new java.awt.Dimension(45, 23));
        jButtonF.setPreferredSize(new java.awt.Dimension(46, 23));
        jButtonF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFActionPerformed(evt);
            }
        });

        jButtonE.setText("E");
        jButtonE.setMaximumSize(new java.awt.Dimension(45, 23));
        jButtonE.setMinimumSize(new java.awt.Dimension(45, 23));
        jButtonE.setPreferredSize(new java.awt.Dimension(46, 23));
        jButtonE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEActionPerformed(evt);
            }
        });

        jButtonD.setText("D");
        jButtonD.setMaximumSize(new java.awt.Dimension(45, 23));
        jButtonD.setMinimumSize(new java.awt.Dimension(45, 23));
        jButtonD.setPreferredSize(new java.awt.Dimension(46, 23));
        jButtonD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDActionPerformed(evt);
            }
        });

        jButtonC.setText("C");
        jButtonC.setMaximumSize(new java.awt.Dimension(45, 23));
        jButtonC.setMinimumSize(new java.awt.Dimension(45, 23));
        jButtonC.setPreferredSize(new java.awt.Dimension(46, 23));
        jButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCActionPerformed(evt);
            }
        });

        jButtonB.setText("B");
        jButtonB.setMaximumSize(new java.awt.Dimension(45, 23));
        jButtonB.setMinimumSize(new java.awt.Dimension(45, 23));
        jButtonB.setPreferredSize(new java.awt.Dimension(46, 23));
        jButtonB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBActionPerformed(evt);
            }
        });

        jButtonA.setText("A");
        jButtonA.setMaximumSize(new java.awt.Dimension(45, 23));
        jButtonA.setMinimumSize(new java.awt.Dimension(45, 23));
        jButtonA.setPreferredSize(new java.awt.Dimension(46, 23));
        jButtonA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAActionPerformed(evt);
            }
        });

        jButtonJ.setText("J");
        jButtonJ.setMaximumSize(new java.awt.Dimension(45, 23));
        jButtonJ.setMinimumSize(new java.awt.Dimension(45, 23));
        jButtonJ.setPreferredSize(new java.awt.Dimension(46, 23));
        jButtonJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJActionPerformed(evt);
            }
        });

        jButtonK.setText("K");
        jButtonK.setMaximumSize(new java.awt.Dimension(45, 23));
        jButtonK.setMinimumSize(new java.awt.Dimension(45, 23));
        jButtonK.setPreferredSize(new java.awt.Dimension(46, 23));
        jButtonK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKActionPerformed(evt);
            }
        });

        jButtonL.setText("L");
        jButtonL.setMaximumSize(new java.awt.Dimension(45, 23));
        jButtonL.setMinimumSize(new java.awt.Dimension(45, 23));
        jButtonL.setPreferredSize(new java.awt.Dimension(46, 23));
        jButtonL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLActionPerformed(evt);
            }
        });

        jButtonM.setText("M");
        jButtonM.setMaximumSize(new java.awt.Dimension(45, 23));
        jButtonM.setMinimumSize(new java.awt.Dimension(45, 23));
        jButtonM.setPreferredSize(new java.awt.Dimension(46, 23));
        jButtonM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMActionPerformed(evt);
            }
        });

        jButtonN.setText("N");
        jButtonN.setMaximumSize(new java.awt.Dimension(45, 23));
        jButtonN.setMinimumSize(new java.awt.Dimension(45, 23));
        jButtonN.setPreferredSize(new java.awt.Dimension(46, 23));
        jButtonN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNActionPerformed(evt);
            }
        });

        jButtonNy.setText("Ñ");
        jButtonNy.setMaximumSize(new java.awt.Dimension(45, 23));
        jButtonNy.setMinimumSize(new java.awt.Dimension(45, 23));
        jButtonNy.setPreferredSize(new java.awt.Dimension(46, 23));
        jButtonNy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNyActionPerformed(evt);
            }
        });

        jButtonO.setText("O");
        jButtonO.setMaximumSize(new java.awt.Dimension(45, 23));
        jButtonO.setMinimumSize(new java.awt.Dimension(45, 23));
        jButtonO.setPreferredSize(new java.awt.Dimension(46, 23));
        jButtonO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOActionPerformed(evt);
            }
        });

        jButtonP.setText("P");
        jButtonP.setMaximumSize(new java.awt.Dimension(45, 23));
        jButtonP.setMinimumSize(new java.awt.Dimension(45, 23));
        jButtonP.setPreferredSize(new java.awt.Dimension(46, 23));
        jButtonP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPActionPerformed(evt);
            }
        });

        jButtonQ.setText("Q");
        jButtonQ.setMaximumSize(new java.awt.Dimension(45, 23));
        jButtonQ.setMinimumSize(new java.awt.Dimension(45, 23));
        jButtonQ.setPreferredSize(new java.awt.Dimension(46, 23));
        jButtonQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQActionPerformed(evt);
            }
        });

        jButtonR.setText("R");
        jButtonR.setMaximumSize(new java.awt.Dimension(45, 23));
        jButtonR.setMinimumSize(new java.awt.Dimension(45, 23));
        jButtonR.setPreferredSize(new java.awt.Dimension(46, 23));
        jButtonR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRActionPerformed(evt);
            }
        });

        jButtonS.setText("S");
        jButtonS.setMaximumSize(new java.awt.Dimension(45, 23));
        jButtonS.setMinimumSize(new java.awt.Dimension(45, 23));
        jButtonS.setPreferredSize(new java.awt.Dimension(46, 23));
        jButtonS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSActionPerformed(evt);
            }
        });

        jButtonT.setText("T");
        jButtonT.setMaximumSize(new java.awt.Dimension(45, 23));
        jButtonT.setMinimumSize(new java.awt.Dimension(45, 23));
        jButtonT.setPreferredSize(new java.awt.Dimension(46, 23));
        jButtonT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTActionPerformed(evt);
            }
        });

        jButtonU.setText("U");
        jButtonU.setMaximumSize(new java.awt.Dimension(45, 23));
        jButtonU.setMinimumSize(new java.awt.Dimension(45, 23));
        jButtonU.setPreferredSize(new java.awt.Dimension(46, 23));
        jButtonU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUActionPerformed(evt);
            }
        });

        jButtonV.setText("V");
        jButtonV.setMaximumSize(new java.awt.Dimension(45, 23));
        jButtonV.setMinimumSize(new java.awt.Dimension(45, 23));
        jButtonV.setPreferredSize(new java.awt.Dimension(46, 23));
        jButtonV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVActionPerformed(evt);
            }
        });

        jButtonW.setText("W");
        jButtonW.setMaximumSize(new java.awt.Dimension(45, 23));
        jButtonW.setMinimumSize(new java.awt.Dimension(45, 23));
        jButtonW.setPreferredSize(new java.awt.Dimension(46, 23));
        jButtonW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWActionPerformed(evt);
            }
        });

        jButtonX.setText("X");
        jButtonX.setMaximumSize(new java.awt.Dimension(45, 23));
        jButtonX.setMinimumSize(new java.awt.Dimension(45, 23));
        jButtonX.setPreferredSize(new java.awt.Dimension(46, 23));
        jButtonX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXActionPerformed(evt);
            }
        });

        jButtonY.setText("Y");
        jButtonY.setMaximumSize(new java.awt.Dimension(45, 23));
        jButtonY.setMinimumSize(new java.awt.Dimension(45, 23));
        jButtonY.setPreferredSize(new java.awt.Dimension(46, 23));
        jButtonY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonYActionPerformed(evt);
            }
        });

        jButtonZ.setText("Z");
        jButtonZ.setMaximumSize(new java.awt.Dimension(45, 23));
        jButtonZ.setMinimumSize(new java.awt.Dimension(45, 23));
        jButtonZ.setPreferredSize(new java.awt.Dimension(46, 23));
        jButtonZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZActionPerformed(evt);
            }
        });

        jButtonNuevoJuego.setText("Nuevo Juego");
        jButtonNuevoJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoJuegoActionPerformed(evt);
            }
        });

        jLabel2.setText("Palabra:");

        jLabelPalabraOculta.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregar Palabra"));
        jPanel3.setToolTipText("Agregar Palabra");

        jButtonAgregarPalabra.setText("Agregar");
        jButtonAgregarPalabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarPalabraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldAgregar)
                    .addComponent(jButtonAgregarPalabra, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAgregarPalabra)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Eliminar Palabra"));

        jButtonEliminarPalabra.setText("Eliminar");
        jButtonEliminarPalabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarPalabraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldEliminar)
                    .addComponent(jButtonEliminarPalabra, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEliminarPalabra)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonNuevoJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonNy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabelPalabraOculta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonNuevoJuego)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabelPalabraOculta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabelImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/alcreta/recursos/0.jpg"))); // NOI18N

        jMenu1.setText("Jugador");
        jMenu1.setToolTipText("");

        jMenuItemJugadorEstadisticas.setText("Estadisticas");
        jMenuItemJugadorEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemJugadorEstadisticasActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemJugadorEstadisticas);

        jMenuItemJugadorCambiar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_SPACE, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemJugadorCambiar.setText("Cambiar");
        jMenuItemJugadorCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemJugadorCambiarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemJugadorCambiar);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metodo que se ejecuta cuando se pulsa el boton
     *
     * @param evt
     */
    private void jButtonAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAActionPerformed
        jButtonA.setEnabled(false);
        if (oAhorcado.comprobacion('a')) {
            jButtonA.setForeground(Color.green);//Background(Color.green);
        } else {
            jButtonA.setForeground(Color.red);//Background(Color.red);
        }
        comprobarEstado();
        dibujar();
    }//GEN-LAST:event_jButtonAActionPerformed

    private void jButtonBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBActionPerformed
        jButtonB.setEnabled(false);
        if (oAhorcado.comprobacion('b')) {
            jButtonB.setForeground(Color.green);//Background(Color.green);
        } else {
            jButtonB.setForeground(Color.red);//Background(Color.red);
        }
        comprobarEstado();
        dibujar();
    }//GEN-LAST:event_jButtonBActionPerformed

    private void jButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCActionPerformed
        jButtonC.setEnabled(false);
        if (oAhorcado.comprobacion('c')) {
            jButtonC.setForeground(Color.green);//Background(Color.green);
        } else {
            jButtonC.setForeground(Color.red);//Background(Color.red);
        }
        comprobarEstado();
        dibujar();
    }//GEN-LAST:event_jButtonCActionPerformed

    private void jButtonDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDActionPerformed
        jButtonD.setEnabled(false);
        if (oAhorcado.comprobacion('d')) {
            jButtonD.setForeground(Color.green);
        } else {
            jButtonD.setForeground(Color.red);
        }
        comprobarEstado();
        dibujar();
    }//GEN-LAST:event_jButtonDActionPerformed

    private void jButtonEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEActionPerformed
        jButtonE.setEnabled(false);
        if (oAhorcado.comprobacion('e')) {
            jButtonE.setForeground(Color.green);
        } else {
            jButtonE.setForeground(Color.red);
        }
        comprobarEstado();
        dibujar();
    }//GEN-LAST:event_jButtonEActionPerformed

    private void jButtonFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFActionPerformed
        jButtonF.setEnabled(false);
        if (oAhorcado.comprobacion('f')) {
            jButtonF.setForeground(Color.green);
        } else {
            jButtonF.setForeground(Color.red);
        }
        comprobarEstado();
        dibujar();
    }//GEN-LAST:event_jButtonFActionPerformed

    private void jButtonGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGActionPerformed
        jButtonG.setEnabled(false);
        if (oAhorcado.comprobacion('g')) {
            jButtonG.setForeground(Color.green);
        } else {
            jButtonG.setForeground(Color.red);
        }
        comprobarEstado();
        dibujar();
    }//GEN-LAST:event_jButtonGActionPerformed

    private void jButtonHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHActionPerformed
        jButtonH.setEnabled(false);
        if (oAhorcado.comprobacion('h')) {
            jButtonH.setForeground(Color.green);
        } else {
            jButtonH.setForeground(Color.red);
        }
        comprobarEstado();
        dibujar();
    }//GEN-LAST:event_jButtonHActionPerformed

    private void jButtonIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIActionPerformed
        jButtonI.setEnabled(false);
        if (oAhorcado.comprobacion('i')) {
            jButtonI.setForeground(Color.green);
        } else {
            jButtonI.setForeground(Color.red);
        }
        comprobarEstado();
        dibujar();
    }//GEN-LAST:event_jButtonIActionPerformed

    private void jButtonJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJActionPerformed
        jButtonJ.setEnabled(false);
        if (oAhorcado.comprobacion('j')) {
            jButtonJ.setForeground(Color.green);
        } else {
            jButtonJ.setForeground(Color.red);
        }
        comprobarEstado();
        dibujar();
    }//GEN-LAST:event_jButtonJActionPerformed

    private void jButtonKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKActionPerformed
        jButtonK.setEnabled(false);
        if (oAhorcado.comprobacion('k')) {
            jButtonK.setForeground(Color.green);
        } else {
            jButtonK.setForeground(Color.red);
        }
        comprobarEstado();
        dibujar();
    }//GEN-LAST:event_jButtonKActionPerformed

    private void jButtonLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLActionPerformed
        jButtonL.setEnabled(false);
        if (oAhorcado.comprobacion('l')) {
            jButtonL.setForeground(Color.green);
        } else {
            jButtonL.setForeground(Color.red);
        }
        comprobarEstado();
        dibujar();
    }//GEN-LAST:event_jButtonLActionPerformed

    private void jButtonMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMActionPerformed
        jButtonM.setEnabled(false);
        if (oAhorcado.comprobacion('m')) {
            jButtonM.setForeground(Color.green);
        } else {
            jButtonM.setForeground(Color.red);
        }
        comprobarEstado();
        dibujar();
    }//GEN-LAST:event_jButtonMActionPerformed

    private void jButtonNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNActionPerformed
        jButtonN.setEnabled(false);
        if (oAhorcado.comprobacion('n')) {
            jButtonN.setForeground(Color.green);
        } else {
            jButtonN.setForeground(Color.red);
        }
        comprobarEstado();
        dibujar();
    }//GEN-LAST:event_jButtonNActionPerformed

    private void jButtonNyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNyActionPerformed
        jButtonNy.setEnabled(false);
        if (oAhorcado.comprobacion('ñ')) {
            jButtonNy.setForeground(Color.green);
        } else {
            jButtonNy.setForeground(Color.red);
        }
        comprobarEstado();
        dibujar();
    }//GEN-LAST:event_jButtonNyActionPerformed

    private void jButtonOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOActionPerformed
        jButtonO.setEnabled(false);
        if (oAhorcado.comprobacion('o')) {
            jButtonO.setForeground(Color.green);
        } else {
            jButtonO.setForeground(Color.red);
        }
        comprobarEstado();
        dibujar();
    }//GEN-LAST:event_jButtonOActionPerformed

    private void jButtonPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPActionPerformed
        jButtonP.setEnabled(false);
        if (oAhorcado.comprobacion('p')) {
            jButtonP.setForeground(Color.green);
        } else {
            jButtonP.setForeground(Color.red);
        }
        comprobarEstado();
        dibujar();
    }//GEN-LAST:event_jButtonPActionPerformed

    private void jButtonQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQActionPerformed
        jButtonQ.setEnabled(false);
        if (oAhorcado.comprobacion('q')) {
            jButtonQ.setForeground(Color.green);
        } else {
            jButtonQ.setForeground(Color.red);
        }
        comprobarEstado();
        dibujar();
    }//GEN-LAST:event_jButtonQActionPerformed

    private void jButtonRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRActionPerformed
        jButtonR.setEnabled(false);
        if (oAhorcado.comprobacion('r')) {
            jButtonR.setForeground(Color.green);
        } else {
            jButtonR.setForeground(Color.red);
        }
        comprobarEstado();
        dibujar();
    }//GEN-LAST:event_jButtonRActionPerformed

    private void jButtonSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSActionPerformed
        jButtonS.setEnabled(false);
        if (oAhorcado.comprobacion('s')) {
            jButtonS.setForeground(Color.green);
        } else {
            jButtonS.setForeground(Color.red);
        }
        comprobarEstado();
        dibujar();
    }//GEN-LAST:event_jButtonSActionPerformed

    private void jButtonTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTActionPerformed
        jButtonT.setEnabled(false);
        if (oAhorcado.comprobacion('t')) {
            jButtonT.setForeground(Color.green);
        } else {
            jButtonT.setForeground(Color.red);
        }
        comprobarEstado();
        dibujar();
    }//GEN-LAST:event_jButtonTActionPerformed

    private void jButtonUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUActionPerformed
        jButtonU.setEnabled(false);
        if (oAhorcado.comprobacion('u')) {
            jButtonU.setForeground(Color.green);
        } else {
            jButtonU.setForeground(Color.red);
        }
        comprobarEstado();
        dibujar();
    }//GEN-LAST:event_jButtonUActionPerformed

    private void jButtonVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVActionPerformed
        jButtonV.setEnabled(false);
        if (oAhorcado.comprobacion('v')) {
            jButtonV.setForeground(Color.green);
        } else {
            jButtonV.setForeground(Color.red);
        }
        comprobarEstado();
        dibujar();
    }//GEN-LAST:event_jButtonVActionPerformed

    private void jButtonWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWActionPerformed
        jButtonW.setEnabled(false);
        if (oAhorcado.comprobacion('w')) {
            jButtonW.setForeground(Color.green);
        } else {
            jButtonW.setForeground(Color.red);
        }
        comprobarEstado();
        dibujar();
    }//GEN-LAST:event_jButtonWActionPerformed

    private void jButtonXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXActionPerformed
        jButtonX.setEnabled(false);
        if (oAhorcado.comprobacion('x')) {
            jButtonX.setForeground(Color.green);
        } else {
            jButtonX.setForeground(Color.red);
        }
        comprobarEstado();
        dibujar();
    }//GEN-LAST:event_jButtonXActionPerformed

    private void jButtonYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonYActionPerformed
        jButtonY.setEnabled(false);
        if (oAhorcado.comprobacion('y')) {
            jButtonY.setForeground(Color.green);
        } else {
            jButtonY.setForeground(Color.red);
        }
        comprobarEstado();
        dibujar();
    }//GEN-LAST:event_jButtonYActionPerformed

    private void jButtonZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZActionPerformed
        jButtonZ.setEnabled(false);
        if (oAhorcado.comprobacion('z')) {
            jButtonZ.setForeground(Color.green);
        } else {
            jButtonZ.setForeground(Color.red);
        }
        comprobarEstado();
        dibujar();
    }//GEN-LAST:event_jButtonZActionPerformed

    private void jButtonEliminarPalabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarPalabraActionPerformed
        oAhorcado.eliminarPalabra(jTextFieldEliminar.getText());
        jTextFieldEliminar.setText("");
    }//GEN-LAST:event_jButtonEliminarPalabraActionPerformed

    private void jButtonNuevoJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoJuegoActionPerformed
        resetearJuego();
    }//GEN-LAST:event_jButtonNuevoJuegoActionPerformed

    private void jButtonAgregarPalabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarPalabraActionPerformed
        if (jTextFieldAgregar.getText().matches("^[a-zA-Z]+$")) {
            oAhorcado.añadirPalabra(jTextFieldAgregar.getText());
            jTextFieldAgregar.setText("");
        } else {
            mensaje("Numeros y caracteres especiales no permitidos");
        }
    }//GEN-LAST:event_jButtonAgregarPalabraActionPerformed

    private void jMenuItemJugadorCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemJugadorCambiarActionPerformed
        oAhorcado.guardarJugador();
        setVisible(false);
        Login oLogin = new Login(this);
    }//GEN-LAST:event_jMenuItemJugadorCambiarActionPerformed

    private void jMenuItemJugadorEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemJugadorEstadisticasActionPerformed
        int pa = oAhorcado.getoJugador().getPalabrasAcertadas();
        int pf = oAhorcado.getoJugador().getPalabrasFalladas();
        int la = oAhorcado.getoJugador().getLetrasAcertadas();
        int lf = oAhorcado.getoJugador().getLetrasFalladas();
        mensaje("Puntuación: " + (pa * 200 + (-pf * 50) + la * 5 + (-lf)) + "\n"
                + "Palabras Acertadas: " + pa + "\n"
                + "Palabras Falladas: " + pf + "\n"
                + "Letras Acertadas: " + la + "\n"
                + "Letras Falladas: " + lf);
    }//GEN-LAST:event_jMenuItemJugadorEstadisticasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Gui().setVisible(false);
        });
    }

    /**
     * Actualiza la palabra a adivinar
     */
    public void dibujar() {
        jLabelPalabraOculta.setText(oAhorcado.getPalabraOculta());
        jLabelImagen.setIcon(new ImageIcon(getClass().getResource("/net/alcreta/recursos/" + oAhorcado.getFallos() + ".jpg")));
    }

    /**
     * Habilita todos los botones, pone las letras negras e inicia nuevo juego
     */
    public void resetearJuego() {

        jButtonA.setForeground(Color.black);
        jButtonB.setForeground(Color.black);
        jButtonC.setForeground(Color.black);
        jButtonD.setForeground(Color.black);
        jButtonE.setForeground(Color.black);
        jButtonF.setForeground(Color.black);
        jButtonG.setForeground(Color.black);
        jButtonH.setForeground(Color.black);
        jButtonI.setForeground(Color.black);
        jButtonJ.setForeground(Color.black);
        jButtonK.setForeground(Color.black);
        jButtonL.setForeground(Color.black);
        jButtonM.setForeground(Color.black);
        jButtonN.setForeground(Color.black);
        jButtonNy.setForeground(Color.black);
        jButtonO.setForeground(Color.black);
        jButtonP.setForeground(Color.black);
        jButtonQ.setForeground(Color.black);
        jButtonR.setForeground(Color.black);
        jButtonS.setForeground(Color.black);
        jButtonT.setForeground(Color.black);
        jButtonU.setForeground(Color.black);
        jButtonV.setForeground(Color.black);
        jButtonW.setForeground(Color.black);
        jButtonX.setForeground(Color.black);
        jButtonY.setForeground(Color.black);
        jButtonZ.setForeground(Color.black);

        jButtonA.setEnabled(true);
        jButtonB.setEnabled(true);
        jButtonC.setEnabled(true);
        jButtonD.setEnabled(true);
        jButtonE.setEnabled(true);
        jButtonF.setEnabled(true);
        jButtonG.setEnabled(true);
        jButtonH.setEnabled(true);
        jButtonI.setEnabled(true);
        jButtonJ.setEnabled(true);
        jButtonK.setEnabled(true);
        jButtonL.setEnabled(true);
        jButtonM.setEnabled(true);
        jButtonN.setEnabled(true);
        jButtonNy.setEnabled(true);
        jButtonO.setEnabled(true);
        jButtonP.setEnabled(true);
        jButtonQ.setEnabled(true);
        jButtonR.setEnabled(true);
        jButtonS.setEnabled(true);
        jButtonT.setEnabled(true);
        jButtonU.setEnabled(true);
        jButtonV.setEnabled(true);
        jButtonW.setEnabled(true);
        jButtonX.setEnabled(true);
        jButtonY.setEnabled(true);
        jButtonZ.setEnabled(true);
        oAhorcado.nuevoJuego();
        dibujar();
    }

    /**
     * Comprueba si se han cometido mas de 6 fallos o si la palabra ha sido
     * adivinada
     */
    public void comprobarEstado() {
        if (oAhorcado.getFallos() >= 6) {
            gameOver();
            oAhorcado.getoJugador().setPalabrasFalladas(oAhorcado.getoJugador().getPalabrasFalladas() + 1);
            mensaje("Has perdido");
        } else {
            int count = 0;
            for (int i = 0; i < oAhorcado.getPalabraOculta().length(); i++) {
                if (oAhorcado.getPalabraOculta().charAt(i) != '_') {
                    count++;
                }
            }
            if (count == oAhorcado.getPalabraOculta().length()) {
                gameOver();
                oAhorcado.getoJugador().setPalabrasAcertadas(oAhorcado.getoJugador().getPalabrasAcertadas() + 1);
                mensaje("Has ganado");
            }
        }
        oAhorcado.guardarJugador();
    }

    /**
     * Deshabilita todos los botones
     */
    public void gameOver() {
        jButtonA.setEnabled(false);
        jButtonB.setEnabled(false);
        jButtonC.setEnabled(false);
        jButtonD.setEnabled(false);
        jButtonE.setEnabled(false);
        jButtonF.setEnabled(false);
        jButtonG.setEnabled(false);
        jButtonH.setEnabled(false);
        jButtonI.setEnabled(false);
        jButtonJ.setEnabled(false);
        jButtonK.setEnabled(false);
        jButtonL.setEnabled(false);
        jButtonM.setEnabled(false);
        jButtonN.setEnabled(false);
        jButtonNy.setEnabled(false);
        jButtonO.setEnabled(false);
        jButtonP.setEnabled(false);
        jButtonQ.setEnabled(false);
        jButtonR.setEnabled(false);
        jButtonS.setEnabled(false);
        jButtonT.setEnabled(false);
        jButtonU.setEnabled(false);
        jButtonV.setEnabled(false);
        jButtonW.setEnabled(false);
        jButtonX.setEnabled(false);
        jButtonY.setEnabled(false);
        jButtonZ.setEnabled(false);

    }

    /**
     * Crear mensaje emergente
     *
     * @param mensaje Contenido del mensaje
     */
    public static void mensaje(String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonA;
    private javax.swing.JButton jButtonAgregarPalabra;
    private javax.swing.JButton jButtonB;
    private javax.swing.JButton jButtonC;
    private javax.swing.JButton jButtonD;
    private javax.swing.JButton jButtonE;
    private javax.swing.JButton jButtonEliminarPalabra;
    private javax.swing.JButton jButtonF;
    private javax.swing.JButton jButtonG;
    private javax.swing.JButton jButtonH;
    private javax.swing.JButton jButtonI;
    private javax.swing.JButton jButtonJ;
    private javax.swing.JButton jButtonK;
    private javax.swing.JButton jButtonL;
    private javax.swing.JButton jButtonM;
    private javax.swing.JButton jButtonN;
    private javax.swing.JButton jButtonNuevoJuego;
    private javax.swing.JButton jButtonNy;
    private javax.swing.JButton jButtonO;
    private javax.swing.JButton jButtonP;
    private javax.swing.JButton jButtonQ;
    private javax.swing.JButton jButtonR;
    private javax.swing.JButton jButtonS;
    private javax.swing.JButton jButtonT;
    private javax.swing.JButton jButtonU;
    private javax.swing.JButton jButtonV;
    private javax.swing.JButton jButtonW;
    private javax.swing.JButton jButtonX;
    private javax.swing.JButton jButtonY;
    private javax.swing.JButton jButtonZ;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JLabel jLabelPalabraOculta;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemJugadorCambiar;
    private javax.swing.JMenuItem jMenuItemJugadorEstadisticas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextFieldAgregar;
    private javax.swing.JTextField jTextFieldEliminar;
    // End of variables declaration//GEN-END:variables
}
