/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.alcreta.gui;

/**
 * La interfaz de inicio de sesión
 * @author alcreta
 */
public class Login extends javax.swing.JFrame {

    private boolean inicio = false;
    private final Gui oGui;

    /**
     * Creates new form Login
     * @param oGui La interfaz del juego
     */
    public Login(Gui oGui) {
        initComponents();
        setLocationRelativeTo(null);
        toFront();
        setVisible(true);
        this.oGui = oGui;
//        setVisible(true);
//        toFront();
//        repaint();
        
    }

    public boolean isInicio() {
        return inicio;
    }

    public void setInicio(boolean inicio) {
        this.inicio = inicio;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonAceptar = new javax.swing.JButton();
        jPasswordFieldContrasenya = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio Sesión");
        setResizable(false);

        jLabel1.setText("Usuario:");

        jLabel2.setText("Contraseña:");

        jButtonAceptar.setText("Entrar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordFieldContrasenya)
                    .addComponent(jTextFieldUsuario)
                    .addComponent(jButtonAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordFieldContrasenya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        if(jTextFieldUsuario.getText().matches("^[a-zA-Z]+$") && jPasswordFieldContrasenya.getText().matches("^[a-zA-Z]+$")){
        switch (oGui.getoAhorcado().iniciarJugador(jTextFieldUsuario.getText(), jPasswordFieldContrasenya.getText())) {
            case 0:
                Gui.mensaje("Se ha creado el jugador: '" + jTextFieldUsuario.getText() + "' e iniciado sesión");
                oGui.setTitle("Juego Ahorcado - Jugando como \""+jTextFieldUsuario.getText()+"\"");
                oGui.setVisible(true);
                setVisible(false);
                dispose();
                break;
            case 1:
                Gui.mensaje("Se ha iniciado sesion como: " + jTextFieldUsuario.getText());
                oGui.setTitle("Juego Ahorcado - Jugando como \""+jTextFieldUsuario.getText()+"\"");
                oGui.setVisible(true);
                dispose();
                setVisible(false);
                break;
            default:
                Gui.mensaje("Contraseña incorrecta");
        }
        }else{
            Gui.mensaje("Numeros y caracteres especiales no permitidos");
        }
    }//GEN-LAST:event_jButtonAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordFieldContrasenya;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
